[default]
SQLALCHEMY_DATABASE_URI = "sqlite:///vision_scrapping.db"
dotenv_file = ".secrets.toml"
TITLE = "Vision Admin"
USER_ADMIN = "Gabriel Ruiz"
Passord_ADMIN = "G@briel210399"
SECRET_KEY = "G@briel210399"
SESSION_TYPE = "filesystem"
EXTENSIONS = [

    "src.ext.database:init_app",
    "src.ext.auth:init_app",
    "src.ext.commands:init_app",
    "src.ext.session:init_app",
    "src.ext.socket:init_app",
    "src.blueprints.webui:init_app",
]


[production]
SQLALCHEMY_DATABASE_URI = "postgresql://vision_scrapping_user:kYv3KVDiQwiYZx98ZYRDLUna0gNTL7Lg@dpg-cjgg2kj37aks73ccmlp0-a.oregon-postgres.render.com/vision_scrapping"
PORT = "10000"
